services:
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=scrabble
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    # Add a named volume for stable, persistent data
    volumes:
      - scrabble-db-data:/var/lib/postgresql/data
    # Add a healthcheck to ensure the database is ready for connections
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d scrabble"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    # Update depends_on to wait for the db to be healthy, not just started
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=caching
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/scrabble
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

# Define the named volume to ensure data persistence
volumes:
  scrabble-db-data:
